# Generated by Django 6.0.2 on 2026-02-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
