# Generated by Django 6.0.2 on 2026-02-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_create_archive_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", "Not set"), ("en", "English"), ("fi", "Finnish")],
                default="",
                max_length=10,
            ),
        ),
    ]
