# Generated by Django 6.0.2 on 2026-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_create_archive_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otherinfo",
            field=models.TextField(blank=True, default="", verbose_name="Muut yhteystiedot"),
        ),
    ]
