# Generated by Django 6.0.2 on 2026-02-08 16:59

from django.db import migrations


def copy_profile_otherinfo(apps, schema_editor):
    Profile = apps.get_model("kompomaatti", "Profile")
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        profiles = Profile.objects.filter(user=user).values_list("otherinfo", flat=True)
        if profiles:
            user.otherinfo = "\n---\n".join(profiles) if len(profiles) > 1 else profiles[0]
            user.save(update_fields=["otherinfo"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_otherinfo"),
        ("kompomaatti", "0021_add_sorting_indexes"),
    ]

    operations = [
        migrations.RunPython(copy_profile_otherinfo, migrations.RunPython.noop),
    ]
