# Generated by Django 6.0.2 on 2026-03-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_otherinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", "Not set"), ("en", "English"), ("fi", "Finnish")],
                default="",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
