# Generated by Django 2.0.7 on 2018-07-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0002_auto_20180711_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(help_text='Tapahtuma johon kilpailu kuuluu', on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='event',
            field=models.ForeignKey(help_text='Tapahtuma johon kompo kuuluu', on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='tapahtuma'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='compo',
            field=models.ForeignKey(help_text='Kompo johon osallistutaan', on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Compo', verbose_name='kompo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(help_text='Käyttäjä jolle entry kuuluu', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='käyttäjä'),
        ),
        migrations.AlterField(
            model_name='ticketvotecode',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Tapahtuma, johon äänestysavain on assosioitu', null=True, on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='ticketvotecode',
            name='ticket',
            field=models.ForeignKey(blank=True, help_text='Lipputuote jonka avainta käytetään äänestysavaimena', null=True, on_delete=django.db.models.deletion.PROTECT, to='store.TransactionItem', verbose_name='Lipputuote'),
        ),
        migrations.AlterField(
            model_name='votecoderequest',
            name='event',
            field=models.ForeignKey(help_text='Tapahtuma, johon äänestysoikeutta pyydetään', null=True, on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
    ]
