# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kompomaatti', '0002_auto_20150403_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketVoteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, help_text='Aika jolloin avain assosioitiin k\xe4ytt\xe4j\xe4lle.', null=True, verbose_name='Aikaleima')),
                ('associated_to', models.ForeignKey(blank=True, help_text='K\xe4ytt\xe4j\xe4 jolle avain on assosioitu', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='K\xe4ytt\xe4j\xe4')),
                ('event', models.ForeignKey(blank=True, help_text='Tapahtuma, johon \xe4\xe4nestysavain on assosioitu', null=True, on_delete=django.db.models.deletion.CASCADE, to='kompomaatti.Event', verbose_name='Tapahtuma')),
                ('ticket', models.ForeignKey(blank=True, help_text='Lipputuote jonka avainta k\xe4ytet\xe4\xe4n \xe4\xe4nestysavaimena', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.TransactionItem', verbose_name='Lipputuote')),
            ],
            options={
                'verbose_name': 'lippu\xe4\xe4nestusavain',
                'verbose_name_plural': 'lippu\xe4\xe4nestysavaimet',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ticketvotecode',
            unique_together=set([('event', 'ticket'), ('event', 'associated_to')]),
        ),
    ]
