# Generated by Django 2.2.6 on 2019-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0004_entrycollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='platform',
            field=models.CharField(blank=True, help_text='Alusta jolla entry toimii. Voit jättää tyhjäksi jos entry ei sisällä ajettavaa koodia.', max_length=128, null=True, verbose_name='Alusta'),
        ),
    ]
