# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 19:35
from __future__ import unicode_literals

from django.db import migrations
from Instanssi.common.misc import parse_youtube_video_id


def forwards(apps, schema_editor):
    Entry = apps.get_model("kompomaatti", "Entry")
    for entry in Entry.objects.all():
        video_id = parse_youtube_video_id(entry.youtube_url)
        if video_id:
            entry.youtube_url = u'https://www.youtube.com/v/{}'.format(video_id)
            entry.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0004_auto_20160129_2325'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
