# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0005_sslize_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compo',
            name='formats',
            field=models.CharField(default='zip|7z|gz|bz2', help_text='Entrypaketille sallitut tiedostopäätteet pystyviivalla eroteltuna, esim. "png|jpg".', max_length=128, verbose_name='Sallitut tiedostopäätteet'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='image_formats',
            field=models.CharField(default='png|jpg', help_text='Entryn pikkukuvalle sallitut tiedostopäätteet pystyviivalla eroteltuna', max_length=128, verbose_name='Sallitut kuvatiedoston päätteet'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='source_formats',
            field=models.CharField(default='zip|7z|gz|bz2', help_text='Entryn lähdekoodipaketille sallitut tiedostopäätteet pystyviivalla eroteltuna', max_length=128, verbose_name='Sallitut lähdekoodipaketin päätteet'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entryfile',
            field=models.FileField(help_text='Tuotospaketti.', upload_to='kompomaatti/entryfiles/', verbose_name='Tiedosto'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='imagefile_original',
            field=models.ImageField(blank=True, help_text='Edustava kuva teokselle. Ei pakollinen, mutta suositeltava.', upload_to='kompomaatti/entryimages/', verbose_name='Kuva'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sourcefile',
            field=models.FileField(blank=True, help_text='Lähdekoodipaketti.', upload_to='kompomaatti/entrysources/', verbose_name='Lähdekoodi'),
        ),
    ]
