# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kompomaatti', '0006_auto_20161209_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votecoderequest',
            unique_together=set([('event', 'user')]),
        ),
        migrations.AlterField(
            model_name='votecoderequest',
            name='user',
            field=models.ForeignKey(
                verbose_name='K\xe4ytt\xe4j\xe4',
                to=settings.AUTH_USER_MODEL,
                help_text='Pyynn\xf6n esitt\xe4nyt k\xe4ytt\xe4j\xe4',
                unique=False)
        )
    ]
