# Generated by Django 3.2.18 on 2023-03-04 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0006_auto_20210511_0020"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateEntryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("format", models.IntegerField(choices=[(0, "AAC"), (1, "OPUS")])),
                ("file", models.FileField(upload_to="kompomaatti/alternates/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_files",
                        to="kompomaatti.entry",
                    ),
                ),
            ],
        ),
    ]
