# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-11 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kompomaatti', '0007_unique_votecode_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompomaatti.Compo',
                                            verbose_name='kompo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='käyttäjä')),
            ],
            options={
                'verbose_name': 'ääniryhmä',
                'verbose_name_plural': 'ääniryhmät',
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='votes', to='kompomaatti.VoteGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='votegroup',
            unique_together=set([('user', 'compo')]),
        ),
    ]
