# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0008_auto_20180211_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecoderequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Odottaa hyväksyntää'), (1, 'Hyväksytty'), (2, 'Hylätty')], default=0, verbose_name='Tila'),
        ),
    ]
