# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kompomaatti', '0009_add_vcreq_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteCode',
        ),
    ]
