# Generated by Django 3.2.18 on 2023-03-11 21:27

from django.db import migrations, models

import Instanssi.kompomaatti.models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0011_auto_20230311_2226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternateentryfile",
            name="file",
            field=models.FileField(
                upload_to=Instanssi.kompomaatti.models.generate_entry_alternate_file_path
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="entryfile",
            field=models.FileField(
                help_text="Tuotospaketti.",
                upload_to=Instanssi.kompomaatti.models.generate_entry_file_path,
                verbose_name="Tiedosto",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="imagefile_original",
            field=models.ImageField(
                blank=True,
                help_text="Edustava kuva teokselle. Ei pakollinen, mutta suositeltava.",
                upload_to=Instanssi.kompomaatti.models.generate_entry_image_path,
                verbose_name="Kuva",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="sourcefile",
            field=models.FileField(
                blank=True,
                help_text="Lähdekoodipaketti.",
                upload_to=Instanssi.kompomaatti.models.generate_entry_source_path,
                verbose_name="Lähdekoodi",
            ),
        ),
        migrations.AlterField(
            model_name="entrycollection",
            name="file",
            field=models.FileField(blank=True, default=None, null=True, upload_to="kompomaatti/collections"),
        ),
    ]
