# Generated by Django 3.2.18 on 2023-03-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0014_auto_20230312_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tag",
            field=models.CharField(
                help_text="Lyhyt nimi, eg. vuosi",
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Lyhyt esitys",
            ),
        ),
    ]
