# Generated by Django 3.2.18 on 2023-03-13 17:58

from django.db import migrations

import Instanssi.common.youtube.fields


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0017_alter_entry_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(
                blank=True,
                help_text="Linkki teoksen Youtube-videoon.",
                null=True,
                verbose_name="Youtube URL",
            ),
        ),
    ]
