import {
    Autoformat,
    AutoImage,
    AutoLink,
    BlockQuote,
    Bold,
    Code,
    CodeBlock,
    Essentials,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    HorizontalLine,
    Image,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    Indent,
    IndentBlock,
    Italic,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    TableToolbar,
    Underline,
    type EditorConfig,
} from "ckeditor5";

export const editorConfig: EditorConfig = {
    licenseKey: "GPL",
    plugins: [
        Autoformat,
        AutoImage,
        AutoLink,
        BlockQuote,
        Bold,
        Code,
        CodeBlock,
        Essentials,
        FontColor,
        FontFamily,
        FontSize,
        Heading,
        HorizontalLine,
        Image,
        ImageInsertViaUrl,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        Indent,
        IndentBlock,
        Italic,
        Link,
        List,
        MediaEmbed,
        Paragraph,
        Strikethrough,
        Subscript,
        Superscript,
        Table,
        TableToolbar,
        Underline,
    ],
    toolbar: {
        items: [
            "undo",
            "redo",
            "|",
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "code",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "|",
            "subscript",
            "superscript",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "outdent",
            "indent",
            "|",
            "link",
            "insertImage",
            "mediaEmbed",
            "insertTable",
            "|",
            "blockQuote",
            "codeBlock",
            "horizontalLine",
        ],
        shouldNotGroupWhenFull: true,
    },
    image: {
        toolbar: [
            "imageStyle:inline",
            "imageStyle:block",
            "imageStyle:side",
            "|",
            "resizeImage",
            "|",
            "imageTextAlternative",
        ],
        resizeUnit: "%" as const,
        resizeOptions: [
            { name: "resizeImage:original", value: null, label: "Original" },
            { name: "resizeImage:25", value: "25", label: "25%" },
            { name: "resizeImage:50", value: "50", label: "50%" },
            { name: "resizeImage:75", value: "75", label: "75%" },
        ],
    },
    table: {
        contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"],
    },
};
