# Generated by Django 6.0.2 on 2026-02-03 23:05

from django.db import migrations

import Instanssi.common.html.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_storeitem_imagefile_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitem",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(
                help_text="Tuotteen pitkä kuvaus.", verbose_name="Tuotteen kuvaus"
            ),
        ),
    ]
