# Generated by Django 6.0.2 on 2026-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_storeitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storetransaction",
            name="time_created",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Luontiaika"),
        ),
    ]
