# Generated by Django 6.0.2 on 2026-03-01 17:20

import Instanssi.common.html.fields
import Instanssi.store.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0023_alter_competition_options_and_more"),
        ("store", "0011_add_sorting_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="storeitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="storeitemvariant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="storetransaction",
            options={},
        ),
        migrations.AlterModelOptions(
            name="transactionitem",
            options={},
        ),
        migrations.AlterField(
            model_name="receipt",
            name="content",
            field=models.TextField(default=None, null=True, verbose_name="Receipt content"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="mail_from",
            field=models.CharField(max_length=256, verbose_name="Sender address"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="mail_to",
            field=models.CharField(max_length=256, verbose_name="Recipient address"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="params",
            field=models.TextField(default=None, null=True, verbose_name="Send parameters"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="sent",
            field=models.DateTimeField(default=None, null=True, verbose_name="Sent at"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="subject",
            field=models.CharField(max_length=256, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="available",
            field=models.BooleanField(default=False, verbose_name="Available for purchase"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Product description"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="discount_amount",
            field=models.IntegerField(default=-1, verbose_name="Discount threshold"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="discount_percentage",
            field=models.IntegerField(default=0, verbose_name="Discount percentage"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kompomaatti.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="imagefile_original",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=Instanssi.store.models.generate_image_path,
                verbose_name="Product image",
            ),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="is_secret",
            field=models.BooleanField(default=False, verbose_name="Product is secret"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="is_ticket",
            field=models.BooleanField(default=False, verbose_name="Product is a ticket"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="max",
            field=models.IntegerField(verbose_name="Available quantity"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="max_per_order",
            field=models.IntegerField(default=10, verbose_name="Maximum per order"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Product name"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Product price"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Secret key"),
        ),
        migrations.AlterField(
            model_name="storeitem",
            name="sort_index",
            field=models.IntegerField(default=0, verbose_name="Sort order"),
        ),
        migrations.AlterField(
            model_name="storeitemvariant",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Variant name"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="city",
            field=models.CharField(max_length=64, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="company",
            field=models.CharField(blank=True, max_length=128, verbose_name="Company"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="country",
            field=django_countries.fields.CountryField(default="FI", max_length=2, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="firstname",
            field=models.CharField(max_length=64, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="information",
            field=models.TextField(blank=True, verbose_name="Additional information"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="key",
            field=models.CharField(max_length=40, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="lastname",
            field=models.CharField(max_length=64, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="mobile",
            field=models.CharField(blank=True, max_length=64, verbose_name="Mobile phone"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="payment_method_name",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Payment method"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="postalcode",
            field=models.CharField(max_length=16, verbose_name="Postal code"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="street",
            field=models.CharField(max_length=128, verbose_name="Street address"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="telephone",
            field=models.CharField(blank=True, max_length=64, verbose_name="Telephone"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="time_cancelled",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancelled at"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="time_created",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="time_paid",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payment confirmed at"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="time_pending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payment initiated at"),
        ),
        migrations.AlterField(
            model_name="storetransaction",
            name="token",
            field=models.CharField(max_length=255, verbose_name="Service token"),
        ),
        migrations.AlterField(
            model_name="storetransactionevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="storetransactionevent",
            name="data",
            field=models.JSONField(null=True, verbose_name="Event data"),
        ),
        migrations.AlterField(
            model_name="storetransactionevent",
            name="message",
            field=models.CharField(max_length=255, verbose_name="Event message"),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="store.storeitem", verbose_name="Product"
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="key",
            field=models.CharField(max_length=40, unique=True, verbose_name="Key"),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="original_price",
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Original product price"),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Product price"),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="time_delivered",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Delivery time"),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storetransaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.storeitemvariant",
                verbose_name="Product variant",
            ),
        ),
    ]
