# Generated by Django 2.0.7 on 2018-07-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitem",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Tapahtuma johon tuote liittyy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kompomaatti.Event",
                verbose_name="Tapahtuma",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="store.StoreItem",
                verbose_name="Tuote",
            ),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.StoreItemVariant",
                verbose_name="Tuotevariantti",
            ),
        ),
    ]
