# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160123_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='discount_amount',
            field=models.IntegerField(default=-1, help_text='Pienin m\xe4\xe4r\xe4 tuotteita joka oikeuttaa alennukseen (-1 = ei mit\xe4\xe4n)', verbose_name='Alennusm\xe4\xe4r\xe4'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Tuotteen hinta.', max_digits=5, verbose_name='Tuotteen hinta'),
        ),
    ]
