# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160129_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tuotevariantin nimi')),
            ],
            options={
                'verbose_name': 'tuotevariantti',
                'verbose_name_plural': 'tuotevariantit',
            },
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='imagefile_original',
            field=models.ImageField(blank=True, help_text='Edustava kuva tuotteelle.', null=True, upload_to='store/images/', verbose_name='Tuotekuva'),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='country',
            field=django_countries.fields.CountryField(default='FI', max_length=2, verbose_name='Maa'),
        ),
        migrations.AddField(
            model_name='storeitemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreItem'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreItemVariant', verbose_name='Tuotevariantti'),
        ),
    ]
