# Generated by Django 3.2.16 on 2023-01-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20210511_0020"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreTransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Tapahtuman viesti")),
                ("data", models.JSONField(null=True, verbose_name="Tapahtuman data")),
                ("created", models.DateTimeField(verbose_name="Luontiaika")),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.storetransaction"
                    ),
                ),
            ],
        ),
    ]
