# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20161209_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_ticket',
            field=models.BooleanField(default=False, help_text='Tuote on lipputuote, ja sitä voi käyttää esim. kompomaatissa äänestysoikeuden hankkimiseen', verbose_name='Tuote on lipputuote'),
        ),
    ]
