# Generated by Django 3.2.16 on 2023-02-01 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_storetransactionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="transaction",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.storetransaction",
            ),
        ),
        migrations.AlterField(
            model_name="storetransactionevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Luontiaika"),
        ),
    ]
