# Generated by Django 3.2.18 on 2023-03-11 21:27

from django.db import migrations, models

import Instanssi.store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_auto_20230202_0115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitem",
            name="imagefile_original",
            field=models.ImageField(
                blank=True,
                help_text="Edustava kuva tuotteelle.",
                null=True,
                upload_to=Instanssi.store.models.generate_image_path,
                verbose_name="Tuotekuva",
            ),
        ),
    ]
