# Generated by Django 1.11.13 on 2018-07-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'lokimerkintä',
                'verbose_name_plural': 'lokimerkinnät',
            },
        ),
    ]
