# Generated by Django 2.0.7 on 2018-07-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0002_auto_20180711_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblogentry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event'),
        ),
        migrations.AlterField(
            model_name='dblogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
