// This file is auto-generated by @hey-api/openapi-ts

import {
    type Client,
    formDataBodySerializer,
    type Options as Options2,
    type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
    BlogEntriesCreateData,
    BlogEntriesCreateResponses,
    BlogEntriesDestroyData,
    BlogEntriesDestroyResponses,
    BlogEntriesListData,
    BlogEntriesListResponses,
    BlogEntriesPartialUpdateData,
    BlogEntriesPartialUpdateResponses,
    BlogEntriesRetrieveData,
    BlogEntriesRetrieveResponses,
    BlogEntriesUpdateData,
    BlogEntriesUpdateResponses,
    EventsCreateData,
    EventsCreateResponses,
    EventsDestroyData,
    EventsDestroyResponses,
    EventsListData,
    EventsListResponses,
    EventsPartialUpdateData,
    EventsPartialUpdateResponses,
    EventsRetrieveData,
    EventsRetrieveResponses,
    EventsUpdateData,
    EventsUpdateResponses,
    GetSocialAuthUrlsData,
    GetSocialAuthUrlsResponses,
    LoginData,
    LoginErrors,
    LoginResponses,
    LogoutData,
    LogoutResponses,
    UserCompoEntriesCreateData,
    UserCompoEntriesCreateResponses,
    UserCompoEntriesDestroyData,
    UserCompoEntriesDestroyResponses,
    UserCompoEntriesListData,
    UserCompoEntriesListResponses,
    UserCompoEntriesPartialUpdateData,
    UserCompoEntriesPartialUpdateResponses,
    UserCompoEntriesRetrieveData,
    UserCompoEntriesRetrieveResponses,
    UserCompoEntriesUpdateData,
    UserCompoEntriesUpdateResponses,
    UserInfoData,
    UserInfoResponses,
    UsersCreateData,
    UsersCreateResponses,
    UsersDestroyData,
    UsersDestroyResponses,
    UsersListData,
    UsersListResponses,
    UsersPartialUpdateData,
    UsersPartialUpdateResponses,
    UsersRetrieveData,
    UsersRetrieveResponses,
    UsersUpdateData,
    UsersUpdateResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const login = <ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>
) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/auth/login/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const logout = <ThrowOnError extends boolean = false>(
    options?: Options<LogoutData, ThrowOnError>
) => {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/auth/logout/",
        ...options,
    });
};

/**
 * Returns a list of URLs that can be used to begin a social authentication process.
 */
export const getSocialAuthUrls = <ThrowOnError extends boolean = false>(
    options?: Options<GetSocialAuthUrlsData, ThrowOnError>
) => {
    return (options?.client ?? client).get<GetSocialAuthUrlsResponses, unknown, ThrowOnError>({
        responseType: "json",
        url: "/api/v2/auth/social_urls/",
        ...options,
    });
};

export const blogEntriesList = <ThrowOnError extends boolean = false>(
    options?: Options<BlogEntriesListData, ThrowOnError>
) => {
    return (options?.client ?? client).get<BlogEntriesListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/",
        ...options,
    });
};

export const blogEntriesCreate = <ThrowOnError extends boolean = false>(
    options: Options<BlogEntriesCreateData, ThrowOnError>
) => {
    return (options.client ?? client).post<BlogEntriesCreateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const blogEntriesDestroy = <ThrowOnError extends boolean = false>(
    options: Options<BlogEntriesDestroyData, ThrowOnError>
) => {
    return (options.client ?? client).delete<BlogEntriesDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/{id}/",
        ...options,
    });
};

export const blogEntriesRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<BlogEntriesRetrieveData, ThrowOnError>
) => {
    return (options.client ?? client).get<BlogEntriesRetrieveResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/{id}/",
        ...options,
    });
};

export const blogEntriesPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<BlogEntriesPartialUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).patch<
        BlogEntriesPartialUpdateResponses,
        unknown,
        ThrowOnError
    >({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const blogEntriesUpdate = <ThrowOnError extends boolean = false>(
    options: Options<BlogEntriesUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).put<BlogEntriesUpdateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/blog_entries/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const eventsList = <ThrowOnError extends boolean = false>(
    options?: Options<EventsListData, ThrowOnError>
) => {
    return (options?.client ?? client).get<EventsListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/",
        ...options,
    });
};

export const eventsCreate = <ThrowOnError extends boolean = false>(
    options: Options<EventsCreateData, ThrowOnError>
) => {
    return (options.client ?? client).post<EventsCreateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const eventsDestroy = <ThrowOnError extends boolean = false>(
    options: Options<EventsDestroyData, ThrowOnError>
) => {
    return (options.client ?? client).delete<EventsDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/{id}/",
        ...options,
    });
};

export const eventsRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<EventsRetrieveData, ThrowOnError>
) => {
    return (options.client ?? client).get<EventsRetrieveResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/{id}/",
        ...options,
    });
};

export const eventsPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<EventsPartialUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).patch<EventsPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const eventsUpdate = <ThrowOnError extends boolean = false>(
    options: Options<EventsUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).put<EventsUpdateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/events/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const userCompoEntriesList = <ThrowOnError extends boolean = false>(
    options?: Options<UserCompoEntriesListData, ThrowOnError>
) => {
    return (options?.client ?? client).get<UserCompoEntriesListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_compo_entries/",
        ...options,
    });
};

export const userCompoEntriesCreate = <ThrowOnError extends boolean = false>(
    options: Options<UserCompoEntriesCreateData, ThrowOnError>
) => {
    return (options.client ?? client).post<UserCompoEntriesCreateResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_compo_entries/",
        ...options,
        headers: {
            "Content-Type": null,
            ...options.headers,
        },
    });
};

export const userCompoEntriesDestroy = <ThrowOnError extends boolean = false>(
    options: Options<UserCompoEntriesDestroyData, ThrowOnError>
) => {
    return (options.client ?? client).delete<
        UserCompoEntriesDestroyResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_compo_entries/{id}/",
        ...options,
    });
};

export const userCompoEntriesRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<UserCompoEntriesRetrieveData, ThrowOnError>
) => {
    return (options.client ?? client).get<UserCompoEntriesRetrieveResponses, unknown, ThrowOnError>(
        {
            responseType: "json",
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
                {
                    in: "cookie",
                    name: "sessionid",
                    type: "apiKey",
                },
            ],
            url: "/api/v2/user_compo_entries/{id}/",
            ...options,
        }
    );
};

export const userCompoEntriesPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UserCompoEntriesPartialUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).patch<
        UserCompoEntriesPartialUpdateResponses,
        unknown,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_compo_entries/{id}/",
        ...options,
        headers: {
            "Content-Type": null,
            ...options.headers,
        },
    });
};

export const userCompoEntriesUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UserCompoEntriesUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).put<UserCompoEntriesUpdateResponses, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_compo_entries/{id}/",
        ...options,
        headers: {
            "Content-Type": null,
            ...options.headers,
        },
    });
};

export const userInfo = <ThrowOnError extends boolean = false>(
    options?: Options<UserInfoData, ThrowOnError>
) => {
    return (options?.client ?? client).get<UserInfoResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/user_info/",
        ...options,
    });
};

export const usersList = <ThrowOnError extends boolean = false>(
    options?: Options<UsersListData, ThrowOnError>
) => {
    return (options?.client ?? client).get<UsersListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/",
        ...options,
    });
};

export const usersCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersCreateData, ThrowOnError>
) => {
    return (options.client ?? client).post<UsersCreateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const usersDestroy = <ThrowOnError extends boolean = false>(
    options: Options<UsersDestroyData, ThrowOnError>
) => {
    return (options.client ?? client).delete<UsersDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/{id}/",
        ...options,
    });
};

export const usersRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<UsersRetrieveData, ThrowOnError>
) => {
    return (options.client ?? client).get<UsersRetrieveResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/{id}/",
        ...options,
    });
};

export const usersPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPartialUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).patch<UsersPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

export const usersUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateData, ThrowOnError>
) => {
    return (options.client ?? client).put<UsersUpdateResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [
            {
                name: "Authorization",
                type: "apiKey",
            },
            {
                in: "cookie",
                name: "sessionid",
                type: "apiKey",
            },
        ],
        url: "/api/v2/users/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};
