# Generated by Django 3.2.18 on 2023-03-13 13:24

from typing import Any

from django.db import migrations

import Instanssi.common.youtube.fields


def forwards(apps: Any, schema_editor: Any) -> None:
    OtherVideo = apps.get_model("arkisto", "OtherVideo")
    for entry in OtherVideo.objects.all():
        entry.youtube_url = entry.youtube_url_old
        entry.save(update_fields=["youtube_url"])


def backwards(apps: Any, schema_editor: Any) -> None:
    OtherVideo = apps.get_model("arkisto", "OtherVideo")
    for entry in OtherVideo.objects.all():
        entry.youtube_url_old = entry.youtube_url
        entry.save(update_fields=["youtube_url_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("arkisto", "0004_auto_20210511_0020"),
    ]

    operations = [
        migrations.RenameField(
            model_name="othervideo",
            old_name="youtube_url",
            new_name="youtube_url_old",
        ),
        migrations.AddField(
            model_name="othervideo",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(
                help_text="Linkki teoksen Youtube-versioon.", verbose_name="Youtube URL", null=True
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="othervideo",
            name="youtube_url_old",
        ),
        migrations.AlterField(  # Make non-nullable now that all rows have value.
            model_name="othervideo",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(
                help_text="Linkki teoksen Youtube-versioon.", verbose_name="Youtube URL"
            ),
        ),
    ]
