# Generated by Django 6.0.2 on 2026-03-01 17:20

import django.db.models.deletion
from django.db import migrations, models

import Instanssi.common.youtube.fields


class Migration(migrations.Migration):

    dependencies = [
        ("arkisto", "0005_alter_othervideo_youtube_url"),
        ("kompomaatti", "0022_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="othervideo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="othervideocategory",
            options={},
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="arkisto.othervideocategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="othervideo",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(verbose_name="Youtube URL"),
        ),
        migrations.AlterField(
            model_name="othervideocategory",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="Event"
            ),
        ),
        migrations.AlterField(
            model_name="othervideocategory",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
    ]
