# Generated by Django 6.0.2 on 2026-03-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sentnotification",
            options={},
        ),
    ]
