# Generated by Django 2.1.7 on 2019-03-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0003_auto_20180711_2110"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="kompomaatti/collections/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection",
                        to="kompomaatti.Compo",
                    ),
                ),
            ],
        ),
    ]
