# Generated by Django 3.2.18 on 2023-03-11 18:41
from datetime import timedelta

from django.db import migrations


def forwards(apps, schema_editor):
    """Fill in created_at timestamp with something correct enough."""
    Entry = apps.get_model("kompomaatti", "Entry")
    for entry in Entry.objects.filter(created_at__isnull=True):
        add_time = entry.compo.adding_end - timedelta(hours=12)
        entry.created_at = add_time.replace(minute=0, second=0, microsecond=0)
        entry.save(update_fields=["created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0008_auto_20230311_2039"),
    ]

    operations = (migrations.RunPython(forwards),)
