# Generated by Django 3.2.18 on 2023-03-11 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0009_auto_20230311_2041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Luontiaika"),
        ),
    ]
