# Generated by Django 3.2.18 on 2023-03-11 20:26

import django.utils.timezone
from django.db import migrations, models

import Instanssi.kompomaatti.models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0010_auto_20230311_2054"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternateentryfile",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
