# Generated by Django 3.2.18 on 2023-03-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0012_auto_20230311_2327"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EntryCollection",
        ),
    ]
