# Generated by Django 3.2.18 on 2023-03-12 14:33

from django.db import migrations, models

import Instanssi.kompomaatti.models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0013_delete_entrycollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternateentryfile",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=Instanssi.kompomaatti.models.generate_entry_alternate_file_path
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="entryfile",
            field=models.FileField(
                help_text="Tuotospaketti.",
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_file_path,
                verbose_name="Tiedosto",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="imagefile_original",
            field=models.ImageField(
                blank=True,
                help_text="Edustava kuva teokselle. Ei pakollinen, mutta suositeltava.",
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_image_path,
                verbose_name="Kuva",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="sourcefile",
            field=models.FileField(
                blank=True,
                help_text="Lähdekoodipaketti.",
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_source_path,
                verbose_name="Lähdekoodi",
            ),
        ),
    ]
