# Generated by Django 3.2.18 on 2023-03-13 11:38
from typing import Any

from django.db import migrations

import Instanssi.common.youtube.fields


def forwards(apps: Any, schema_editor: Any) -> None:
    Entry = apps.get_model("kompomaatti", "Entry")
    for entry in Entry.objects.all():
        entry.youtube_url = entry.youtube_url_old if entry.youtube_url_old else None
        entry.save(update_fields=["youtube_url"])


def backwards(apps: Any, schema_editor: Any) -> None:
    Entry = apps.get_model("kompomaatti", "Entry")
    for entry in Entry.objects.all():
        entry.youtube_url_old = entry.youtube_url if entry.youtube_url else ""
        entry.save(update_fields=["youtube_url_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0016_auto_20230312_2225"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="youtube_url",
            new_name="youtube_url_old",
        ),
        migrations.AddField(
            model_name="entry",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(
                help_text="Linkki teoksen Youtube-videoon.", null=True, verbose_name="Youtube URL"
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="entry",
            name="youtube_url_old",
        ),
    ]
