# Generated by Django 6.0.1 on 2026-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0018_alter_entry_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Piilottaa tapahtuman julkisesta ja käyttäjä-API:sta",
                verbose_name="Piilotettu",
            ),
        ),
    ]
