# Generated by Django 6.0.2 on 2026-02-03 23:05

from django.db import migrations

import Instanssi.common.html.fields


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0019_event_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Kuvaus"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Kuvaus"),
        ),
    ]
