# Generated by Django 6.0.2 on 2026-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0020_alter_competition_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="start",
            field=models.DateTimeField(
                db_index=True, help_text="Kilpailun aloitusaika.", verbose_name="Kilpailun alku"
            ),
        ),
    ]
