# Generated by Django 6.0.2 on 2026-02-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0021_add_sorting_indexes"),
        ("users", "0007_copy_profile_otherinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
