# Generated by Django 6.0.2 on 2026-03-01 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import Instanssi.common.html.fields
import Instanssi.common.youtube.fields
import Instanssi.kompomaatti.models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0022_delete_profile"),
        ("store", "0011_add_sorting_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={},
        ),
        migrations.AlterModelOptions(
            name="competitionparticipation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="compo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticketvotecode",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={},
        ),
        migrations.AlterModelOptions(
            name="votecoderequest",
            options={},
        ),
        migrations.AlterModelOptions(
            name="votegroup",
            options={},
        ),
        migrations.AlterField(
            model_name="competition",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Competition end"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="Event"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="hide_from_archive",
            field=models.BooleanField(default=False, verbose_name="Hide from archive"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="participation_end",
            field=models.DateTimeField(verbose_name="Participation deadline"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="score_sort",
            field=models.IntegerField(
                choices=[(0, "Highest score first"), (1, "Lowest score first")],
                default=0,
                verbose_name="Score sorting",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="score_type",
            field=models.CharField(max_length=8, verbose_name="Score type"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="show_results",
            field=models.BooleanField(default=False, verbose_name="Show results"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="start",
            field=models.DateTimeField(db_index=True, verbose_name="Competition start"),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kompomaatti.competition",
                verbose_name="Competition",
            ),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="disqualified",
            field=models.BooleanField(default=False, verbose_name="Disqualified"),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="disqualified_reason",
            field=models.TextField(blank=True, verbose_name="Disqualification reason"),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="participant_name",
            field=models.CharField(default="", max_length=32, verbose_name="Participant name"),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="score",
            field=models.FloatField(blank=True, default=0, verbose_name="Score"),
        ),
        migrations.AlterField(
            model_name="competitionparticipation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="adding_end",
            field=models.DateTimeField(verbose_name="Entry adding deadline"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="compo_start",
            field=models.DateTimeField(verbose_name="Compo start time"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="editing_end",
            field=models.DateTimeField(verbose_name="Entry editing deadline"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="entry_sizelimit",
            field=models.IntegerField(default=134217728, verbose_name="Entry size limit"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="entry_view_type",
            field=models.IntegerField(
                choices=[
                    (0, "Nothing"),
                    (1, "Youtube first, then image"),
                    (2, "Image only"),
                    (3, "(deprecated)"),
                ],
                default=0,
                verbose_name="Entry presentation",
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="event"
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="formats",
            field=models.CharField(
                default="zip|7z|gz|bz2", max_length=128, verbose_name="Allowed file extensions"
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="hide_from_archive",
            field=models.BooleanField(default=False, verbose_name="Hide from archive"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="hide_from_frontpage",
            field=models.BooleanField(default=False, verbose_name="Hide from front page"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="image_formats",
            field=models.CharField(
                default="png|jpg", max_length=128, verbose_name="Allowed image file extensions"
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="is_votable",
            field=models.BooleanField(default=True, verbose_name="Votable"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="show_voting_results",
            field=models.BooleanField(default=False, verbose_name="Show results"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="source_formats",
            field=models.CharField(
                default="zip|7z|gz|bz2", max_length=128, verbose_name="Allowed source package extensions"
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="source_sizelimit",
            field=models.IntegerField(default=134217728, verbose_name="Source size limit"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="thumbnail_pref",
            field=models.IntegerField(
                choices=[
                    (0, "Require separate thumbnail."),
                    (1, "Use entry file as thumbnail (only works for png/jpg files)."),
                    (2, "Allow thumbnail (not required)."),
                    (3, "Do not allow thumbnail."),
                ],
                default=2,
                verbose_name="Thumbnail settings",
            ),
        ),
        migrations.AlterField(
            model_name="compo",
            name="voting_end",
            field=models.DateTimeField(verbose_name="Voting end time"),
        ),
        migrations.AlterField(
            model_name="compo",
            name="voting_start",
            field=models.DateTimeField(verbose_name="Voting start time"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="archive_rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="Rank"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="archive_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Score"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="compo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.compo", verbose_name="compo"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="creator",
            field=models.CharField(max_length=64, verbose_name="Creator"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="disqualified",
            field=models.BooleanField(default=False, verbose_name="Disqualified"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="disqualified_reason",
            field=models.TextField(blank=True, verbose_name="Disqualification reason"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="entryfile",
            field=models.FileField(
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_file_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="imagefile_original",
            field=models.ImageField(
                blank=True,
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_image_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="platform",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Platform"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="sourcefile",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=Instanssi.kompomaatti.models.generate_entry_source_path,
                verbose_name="Source code",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="user"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="youtube_url",
            field=Instanssi.common.youtube.fields.YoutubeVideoField(
                blank=True, null=True, verbose_name="Youtube URL"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AlterField(
            model_name="event",
            name="mainurl",
            field=models.URLField(blank=True, verbose_name="Event main page"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="tag",
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name="Short tag"),
        ),
        migrations.AlterField(
            model_name="ticketvotecode",
            name="associated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="ticketvotecode",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kompomaatti.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="ticketvotecode",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.transactionitem",
                verbose_name="Ticket item",
            ),
        ),
        migrations.AlterField(
            model_name="ticketvotecode",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="compo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kompomaatti.compo", verbose_name="compo"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kompomaatti.entry", verbose_name="entry"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="rank",
            field=models.IntegerField(verbose_name="Rank"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user"
            ),
        ),
        migrations.AlterField(
            model_name="votecoderequest",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="kompomaatti.event",
                verbose_name="Event",
            ),
        ),
        migrations.AlterField(
            model_name="votecoderequest",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Pending approval"), (1, "Approved"), (2, "Rejected")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="votecoderequest",
            name="text",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="votecoderequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
        migrations.AlterField(
            model_name="votegroup",
            name="compo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kompomaatti.compo", verbose_name="compo"
            ),
        ),
        migrations.AlterField(
            model_name="votegroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user"
            ),
        ),
    ]
