# Generated by Django 6.0.2 on 2026-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0023_alter_competition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="order_index",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Order index"),
        ),
    ]
