# Generated by Django 6.0.2 on 2026-03-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0023_alter_competition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compo",
            name="live_voting_enabled",
            field=models.BooleanField(default=False, verbose_name="Live voting enabled"),
        ),
        migrations.AddField(
            model_name="entry",
            name="live_voting_order",
            field=models.IntegerField(default=0, verbose_name="Live voting reveal order"),
        ),
        migrations.AddField(
            model_name="entry",
            name="live_voting_revealed",
            field=models.BooleanField(default=False, verbose_name="Revealed in live voting"),
        ),
        migrations.CreateModel(
            name="LiveVotingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("voting_open", models.BooleanField(default=False, verbose_name="Voting open")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "compo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_voting_state",
                        to="kompomaatti.compo",
                    ),
                ),
                (
                    "current_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kompomaatti.entry",
                    ),
                ),
            ],
        ),
    ]
