# Generated by Django 6.0.2 on 2026-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kompomaatti", "0025_live_voting"),
    ]

    operations = [
        migrations.AddField(
            model_name="compo",
            name="imagefile_sizelimit",
            field=models.IntegerField(default=6291456, verbose_name="Image file size limit"),
        ),
    ]
