# Generated by Django 1.11.13 on 2018-07-11 17:54
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kompomaatti", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kompomaatti.Event",
                verbose_name="Tapahtuma",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Käyttäjä",
            ),
        ),
    ]
