# Generated by Django 6.0.2 on 2026-02-04 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_upload", "0007_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Aika"
            ),
        ),
    ]
