# Generated by Django 6.0.2 on 2026-03-01 17:20

import Instanssi.admin_upload.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_upload", "0008_add_sorting_indexes"),
        ("kompomaatti", "0022_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={},
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="Event"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=Instanssi.admin_upload.models.generate_file_path,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
