# Generated by Django 1.11.13 on 2018-07-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Videon nimi.', max_length=64, verbose_name='Nimi')),
                ('description', models.TextField(help_text='Videon kuvaus.', verbose_name='Kuvaus')),
                ('youtube_url', models.URLField(blank=True, help_text='Linkki teoksen Youtube-versioon.', verbose_name='Youtube URL')),
            ],
            options={
                'verbose_name': 'muu video',
                'verbose_name_plural': 'muut videot',
            },
        ),
        migrations.CreateModel(
            name='OtherVideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategorian nimi', max_length=64, verbose_name='Nimi')),
            ],
            options={
                'verbose_name': 'videokategoria',
                'verbose_name_plural': 'videokategoriat',
            },
        ),
    ]
