# Generated by Django 3.2.2 on 2021-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkisto', '0003_auto_20180711_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othervideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='othervideocategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
