# Generated by Django 2.0.7 on 2018-07-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ircmessage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='npsong',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='screenconfig',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kompomaatti.Event', verbose_name='Tapahtuma'),
        ),
    ]
