# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 02:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0002_auto_20150403_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistvideo',
            name='index',
            field=models.IntegerField(help_text='Indeksi toistolistan j\xe4rjestelemiseen. Pienimm\xe4ll\xe4 numerolla varustetut toistetaan ensimm\xe4iseksi.', verbose_name='J\xe4rjestysindeksi'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='name',
            field=models.CharField(help_text='Videon nimi tai otsikko.', max_length=64, verbose_name='Nimi'),
        ),
    ]
