# Generated by Django 3.2.18 on 2023-03-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screenshow", "0003_auto_20210511_0020"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="event",
        ),
        migrations.RemoveField(
            model_name="npsong",
            name="event",
        ),
        migrations.RemoveField(
            model_name="playlistvideo",
            name="event",
        ),
        migrations.RemoveField(
            model_name="screenconfig",
            name="event",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="event",
        ),
        migrations.DeleteModel(
            name="IRCMessage",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="NPSong",
        ),
        migrations.DeleteModel(
            name="PlaylistVideo",
        ),
        migrations.DeleteModel(
            name="ScreenConfig",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
    ]
