# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Tiedosto'),
        ),
    ]
