# Generated by Django 3.2.16 on 2022-12-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_blog', '0004_auto_20210511_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
