# Generated by Django 3.2.18 on 2023-03-11 21:23

from django.db import migrations, models

import Instanssi.ext_programme.models


class Migration(migrations.Migration):

    dependencies = [
        ("ext_programme", "0004_alter_programmeevent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmeevent",
            name="icon2_original",
            field=models.ImageField(
                blank=True,
                help_text="Kuva 2 tapahtumalle.",
                upload_to=Instanssi.ext_programme.models.generate_icon_path,
                verbose_name="Kuva 2",
            ),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="icon_original",
            field=models.ImageField(
                blank=True,
                help_text="Kuva 1 tapahtumalle.",
                upload_to=Instanssi.ext_programme.models.generate_icon_path,
                verbose_name="Kuva 1",
            ),
        ),
    ]
