# Generated by Django 6.0.2 on 2026-02-03 23:05

from django.db import migrations

import Instanssi.common.html.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ext_programme", "0007_auto_20230312_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmeevent",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(blank=True, verbose_name="Kuvaus"),
        ),
    ]
