# Generated by Django 6.0.2 on 2026-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ext_programme", "0008_alter_programmeevent_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmeevent",
            name="start",
            field=models.DateTimeField(
                db_index=True, help_text="Tapahtuman alkamisaika.", verbose_name="Alku"
            ),
        ),
    ]
