# Generated by Django 6.0.2 on 2026-03-01 17:20

import django.db.models.deletion
from django.db import migrations, models

import Instanssi.common.html.fields
import Instanssi.ext_programme.models


class Migration(migrations.Migration):

    dependencies = [
        ("ext_programme", "0009_add_sorting_indexes"),
        ("kompomaatti", "0022_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programmeevent",
            options={},
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="description",
            field=Instanssi.common.html.fields.SanitizedHtmlField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="Event"
            ),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="event_type",
            field=models.IntegerField(
                choices=[(0, "Simple"), (1, "Detailed")], default=0, verbose_name="Event type"
            ),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Github"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="home_url",
            field=models.URLField(blank=True, verbose_name="Home URL"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="icon2_original",
            field=models.ImageField(
                blank=True,
                max_length=255,
                upload_to=Instanssi.ext_programme.models.generate_icon_path,
                verbose_name="Image 2",
            ),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="icon_original",
            field=models.ImageField(
                blank=True,
                max_length=255,
                upload_to=Instanssi.ext_programme.models.generate_icon_path,
                verbose_name="Image 1",
            ),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="place",
            field=models.CharField(blank=True, max_length=64, verbose_name="Place"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="presenters",
            field=models.CharField(blank=True, max_length=256, verbose_name="Presenters"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="presenters_titles",
            field=models.CharField(blank=True, max_length=256, verbose_name="Titles"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="start",
            field=models.DateTimeField(db_index=True, verbose_name="Start"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="programmeevent",
            name="wiki_url",
            field=models.URLField(blank=True, verbose_name="Wikipedia"),
        ),
    ]
