# Generated by Django 5.0.3 on 2024-03-28 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ext_blog", "0005_delete_blogcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Aika"),
        ),
    ]
