# Generated by Django 5.0.3 on 2024-04-01 22:05

from django.db import migrations

import Instanssi.common.html.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ext_blog", "0006_alter_blogentry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="text",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Teksti"),
        ),
    ]
