# Generated by Django 6.0.2 on 2026-03-01 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import Instanssi.common.html.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ext_blog", "0008_add_sorting_indexes"),
        ("kompomaatti", "0022_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogentry",
            options={},
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kompomaatti.event", verbose_name="Event"
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="text",
            field=Instanssi.common.html.fields.SanitizedHtmlField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
