name: Kompomaatti CI

on:
  workflow_dispatch:
  push:
    paths:
      - "kompomaatti/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kompomaatti/**"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kompomaatti
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, test and build
      run: |
        cp src/config.dist.ts src/config.ts
        yarn --frozen-lockfile
        yarn run test
        yarn run build
      env:
        CI: true
